--
-- Tabellenstruktur für Tabelle `player`
--

CREATE TABLE IF NOT EXISTS `player` (
  `id` int(10) NOT NULL auto_increment,
  `login` varchar(50) collate latin1_german2_ci NOT NULL default '',
  `name` varchar(50) collate latin1_german2_ci default NULL,
  `description` text collate latin1_german2_ci,
  `password` varchar(50) collate latin1_german2_ci NOT NULL default '',
  `email` varchar(100) collate latin1_german2_ci NOT NULL default '',
  `register_email` varchar(100) collate latin1_german2_ci NOT NULL default '',
  `sms` varchar(20) collate latin1_german2_ci default NULL,
  `ip` varchar(15) collate latin1_german2_ci NOT NULL default '000.000.000.000',
  `lastseen` int(11) NOT NULL default '0',
  `religion` tinyint(3) default '1',
  `pos` int(11) default NULL,
  `gold` bigint(20) NOT NULL default '60000',
  `wood` int(10) NOT NULL default '4000',
  `iron` int(10) NOT NULL default '0',
  `stone` int(10) NOT NULL default '4000',
  `rp` int(10) NOT NULL default '50',
  `recruiter` int(11) default NULL,
  `bonuspoints` int(10) NOT NULL default '0',
  `lastclickbonuspoints` int(11) NOT NULL default '0',
  `points` int(10) NOT NULL default '0',
  `pointsavg` bigint(20) NOT NULL default '1',
  `pointsupd` int(11) NOT NULL default '1',
  `clan` smallint(5) default NULL,
  `clanstatus` smallint(5) NOT NULL default '0',
  `clanapplication` smallint(5) default NULL,
  `clanapplicationtext` text collate latin1_german2_ci,
  `signature` text collate latin1_german2_ci,
  `status` tinyint(3) default NULL,
  `statusdescription` text collate latin1_german2_ci,
  `nooblevel` tinyint(4) NOT NULL default '5',
  `holiday` int(11) NOT NULL default '0',
  `activationkey` varchar(10) collate latin1_german2_ci default NULL,
  `activationtime` int(11) default NULL,
  `regtime` int(11) NOT NULL default '0',
  `mapsize` smallint(5) NOT NULL default '4040',
  `mapversion` char(2) collate latin1_german2_ci NOT NULL default 'v3',
  `cc_towns` tinyint(1) NOT NULL default '0',
  `cc_messages` tinyint(1) NOT NULL default '0',
  `cc_resources` tinyint(1) NOT NULL default '0',
  `lastres` int(11) NOT NULL default '0',
  `gfx_path` varchar(100) collate latin1_german2_ci NOT NULL default '',
  `hwstatus` smallint(6) NOT NULL default '0',
  `settings` bigint(20) NOT NULL default '0',
  `toplist` tinyint(3) default NULL,
  `avatar` tinyint(1) NOT NULL default '0',
  `tutorial` int(11) NOT NULL default '0' COMMENT 'Level des Tutorials',
  `markdelete` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `login` (`login`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_german2_ci;
